
@host=localhost
@port=3000

@basePath=http://{{host}}:{{port}}/api



###
# Get all employees
GET {{basePath}}/employees
Content-Type: application/json
Authorization: Basic john:fun123

### 
# get single employee
GET {{basePath}}/employees/2
Content-Type: application/json
Authorization: Basic mary:test123

### 
# Insert new employee
POST {{basePath}}/employees
Content-Type: application/json
Authorization: Basic mary:test123

{
  "firstName": "Tresten",
  "lastName": "Pool",
  "email": "trestenpool@gmail.com"
}

### 
# Update employee
PUT {{basePath}}/employees
Content-Type: application/json
Authorization: Basic mary:test123

{
  "id": 8,
  "firstName": "Trestenz",
  "lastName": "Pool",
  "email": "trestenpool@gmail.com"
}



### 
# Delete employee
DELETE  {{basePath}}/employees/2
Content-Type: application/json
Authorization: Basic susan:fun123