###
# Get all employees
GET http://{{host}}:{{port}}/api/employees

###
# get single employee
GET http://{{host}}:{{port}}/api/employees/7

###
# Insert new employee
POST http://{{host}}:{{port}}/api/employees HTTP/1.1
Content-Type: application/json

{
  "first_name": "Noah",
  "last_name": "Pool",
  "email": "noahpool@gmail.com"
}

###
# Update employee
PUT http://{{host}}:{{port}}/api/employees/7 HTTP/1.1
Content-Type: application/json

{
  "first_name": "Tresten",
  "last_name": "Pool",
  "email": "trestenpool@gmail.com"
}

###
# Delete employee
DELETE http://{{host}}:{{port}}/api/employees/7